### PR TITLE
Tinymce

### PR DESCRIPTION
**Pull request by Artemkarganov**
Added tinymce for the description input field

### CODE REVIEW

**Comment by galulex** [comment]
Add to `.gitignore` your `public/uploads` folder

**Comment by Artemkarganov** [comment]
Added public/uploads to .gitignore

**Comment by galulex** [comment]
Remove all the `public/uploads` files from Pull request

**Comment by galulex** [comment]
now you can add `public/uploads` to `.gitignore`. Also there is one left

**Comment by galulex** [comment]
:+1:

**Pull request merged**
